apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: my-eks-cluster
  region: eu-north-1
  version: "1.27"

nodeGroups:
  - name: ng-1
    instanceType: m5.large
    desiredCapacity: 2
    maxSize: 3
    minSize: 1
    volumeSize: 80
    volumeType: gp2

