kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: sa-rolebinding
  namespace: nginx-ns
subjects:
- kind: ServiceAccount
  name: nginx-service-account
  namespace: nginx-ns
roleRef:
  kind: Role
  name: sa-role
  apiGroup: rbac.authorization.k8s.io
